spring:
  application:
    name: commons-blocks-profiles-service
  profiles:
    active: ${COMMONS_ENVIRONMENT_PROFILE:dev}
  config:
    import: "optional:configserver:${COMMONS_CONFIG_SERVER_URL:https://dev.platformcommons.org/commons-config}"



commons:
  platform:
    service:
      datasource:
        db_name: commons_blocks_profiles_db

server:
  port: ${SERVER_PORT:9992}
  servlet:
    context-path: /commons-blocks-profiles-service